### PR TITLE
Allow MaxAuthRetries to be configurable for SSH server config

### PR DESCRIPTION
**Pull request by serenakeating**
We need to configure the maxAuthRetries default value.

### CODE REVIEW

**Comment by serenakeating** [comment]
Not sure why this build failed, looks unrelated to the changes I made.

**Comment by chris-rock** [comment]
Hi @serenakeating Thank you very much for adding this feature. I take a look, why the build failed.

**Comment by chris-rock** [comment]
Thank you very much for you contribution @serenakeating I apologize for the delayed merge. Has been a busy week. Let me know if you need anything.

**Comment by serenakeating** [comment]
Are you able to make a new release that has this pull request merged?

**Pull request merged**
